apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-server-staging
  namespace: argocd
  labels:
    example.org/environment: staging
spec:
  project: default
  source:
    repoURL: https://github.com/ns3777k/argocd-monorepo
    targetRevision: HEAD
    path: apps/charts/auth-server/staging
    helm:
      valuesObject:
        nameOverride: auth-server-staging
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
