apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: hello
  name: hello-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-2
spec:
  selector:
    matchLabels:
      app: helloworld-2
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld-2
    spec:
      containers:
      - name: helloworld-2
        image: karthequian/helloworld:latest
        ports:
        - containerPort: 80