apiVersion: v2
name: auth-server
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: common-library
    version: 0.1.0
    repository: file://../../charts/common-library